/// <summary>
/// JSON to Data Contract (or JSON.NET) types
/// https://jsontodatacontract.azurewebsites.net/
/// ------------------------------------------------------------------------------
///  <auto-generated>
///      This code was generated by a tool.
///      Runtime Version:4.0.30319.42000
/// 
///      Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
///  </auto-generated>
/// ------------------------------------------------------------------------------
/// </summary>
namespace PS4CheaterNeo
{
    // Type created for JSON at <<root>>
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LanguageJson
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MainForm MainForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SendPayloadForm SendPayloadForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewAddressForm NewAddressForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public QueryForm QueryForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public HexEditorForm HexEditorForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PointerFinderForm PointerFinderForm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public OptionForm OptionForm;
    }

    // Type created for JSON at <<root>> --> MainForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MainForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripLockEnable;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripAutoRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripSendToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripOpenToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripSaveToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripNewQueryToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripAddToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripHexViewToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripRefreshCheatToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripExpandAllToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripCollapseAllToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripLockEnableToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripAutoRefreshToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripSettingsToolTipText;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToolStripProcessInfoMsg;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewDel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewType;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewActive;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewValue;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewSection;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewSID;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewDescription;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuHexEditor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuUnlock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuActive;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuEdit;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuCopyAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuFindPointer;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridMenuDelete;
    }

    // Type created for JSON at <<root>> --> SendPayloadForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendPayloadForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendPayloadBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OKBtn;
    }

    // Type created for JSON at <<root>> --> NewAddressForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewAddressForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LockBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointerBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaveBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CloseBtn;
    }

    // Type created for JSON at <<root>> --> QueryForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QueryForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewType;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewValue;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewHex;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewSection;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewAddToCheatGrid;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewSelectAll;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewHexEditor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewCopyAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewDump;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultViewFindPointer;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetProcessesBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewName;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewProt;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewLength;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewSID;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewOffset;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewEnd;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewHexEditor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewCheck;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewCheckAll;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewUnCheckAll;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewInvertChecked;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewCheckContains;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewUnCheckContains;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewCheckProt;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewUnCheckProt;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewCheckAllHidden;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewUnCheckAllHidden;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewDump;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewImport;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrMinLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrMaxLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrIsFilterBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectAllBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlignmentBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFilterSizeBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFilterBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CloneScanBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoPauseBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoResumeBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlowMotionBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SimpleValuesBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value0Label;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value1Label;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueAndLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompareFirstBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefreshBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextScan;
    }

    // Type created for JSON at <<root>> --> HexEditorForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HexEditorForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoRefreshBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefreshBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommitBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddToCheatGridBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LittleEndianBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForwardBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FindBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SwapBytesBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssemblerBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupBoxAsm;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexViewMenuByteGroup;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexViewMenuGroupSize;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexViewMenuCopyAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexViewMenuJumpToAddress;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexViewMenuJumpToOffset;
    }

    // Type created for JSON at <<root>> --> PointerFinderForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PointerFinderForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LevelLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxRangeLabel;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsInitScan;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FastScanBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NegativeOffsetBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFilterBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterRuleBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFilterSizeBox;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterSizeRuleBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaveBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadBtn;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointerListViewAddToCheatGrid;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointerListViewSelectAll;
    }

    // Type created for JSON at <<root>> --> OptionForm
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OptionForm
    {

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tree_General;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tree_Cheat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tree_Query;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tree_HexEditor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tree_UI;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Connect;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_SendPayload;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_UI;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_PS4Tool;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Option;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Cheat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_CheatLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_CheatRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Query;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Floating;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Filter;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Result;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_SectionView;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Find;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group_Hex;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color Theme")]
        public string group_Color_0020_Theme;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color Ui")]
        public string group_Color_0020_Ui;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color Main")]
        public string group_Color_0020_Main;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color Query")]
        public string group_Color_0020_Query;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color HexEditor")]
        public string group_Color_0020_HexEditor;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color PointerFinder")]
        public string group_Color_0020_PointerFinder;

        [System.Runtime.Serialization.DataMemberAttribute(Name = "group_Color SendPayload")]
        public string group_Color_0020_SendPayload;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PS4IP;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PS4Port;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PS4FWVersion;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollapsibleContainer;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UILanguage;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIFont;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UIOpacity;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridViewGroupByEnabled;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatGridGroupRefreshThreshold;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PS4DBGMutexFactor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayChangesListWhenSaving;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatCellDirtyValueCommit;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifySectionWhenLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatAutoRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatAutoRefreshShowStatus;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheatAutoRefreshTimerInterval;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifySectionWhenRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoPerformGetProcesses;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultProcess;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxQueryThreads;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryBufferSize;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinResultAccessFactor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinResultAccessFactorThreshold;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UndoScan;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanAutoPause;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScanAutoResume;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowSearchSizeFirstScan;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnknownInitialScanDoNotSkip0;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloatingResultExact;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloatingSimpleValueExponents;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterQuery;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionFilterKeys;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterSizeQuery;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionFilterSize;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxResultShow;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewFullRowSelect;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectionViewDetectHiddenSection;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetectHiddenSectionStartFromTheEnd;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastHiddenSectionLengthHex;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HiddenSectionStartAtPreviousEnd;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WriteHiddenSectionConf;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoRefreshTimerInterval;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexInfoDash;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoFindClosestChangedPosition;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputIsHexFormat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsingLittleEndian;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorTheme;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UiForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UiBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainToolStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridViewRowIndexForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridViewBackgroundColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridViewBaseRowColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridViewGridColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridCellForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainCheatGridCellBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryStatusStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryAlignmentBoxForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueryScanBtnBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewFilterForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewFilterBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewFilterSizeForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewFilterSizeBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewExecutableForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewNoNameForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewNoName2ForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewHiddenForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewItemCheck1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuerySectionViewItemCheck2BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexEditorChangedFinishForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexEditorShadowSelectionColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HexEditorZeroBytesForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointerFinderStatusStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointerFinderScanBtnBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendPayloadStatusStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PS4IP;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PS4Port;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PS4FWVersion;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UILanguage;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UIFont;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UIOpacity;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CollapsibleContainer;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatGridViewGroupByEnabled;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatGridGroupRefreshThreshold;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PS4DBGMutexFactor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_DisplayChangesListWhenSaving;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatCellDirtyValueCommit;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_VerifySectionWhenLock;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatAutoRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatAutoRefreshShowStatus;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_CheatAutoRefreshTimerInterval;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_VerifySectionWhenRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_AutoPerformGetProcesses;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_DefaultProcess;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MaxQueryThreads;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QueryBufferSize;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MinResultAccessFactor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MinResultAccessFactorThreshold;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UndoScan;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_ScanAutoPause;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_ScanAutoResume;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_ShowSearchSizeFirstScan;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UnknownInitialScanDoNotSkip0;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_FloatingResultExact;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_FloatingSimpleValueExponents;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_FilterQuery;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_SectionFilterKeys;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_FilterSizeQuery;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_SectionFilterSize;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MaxResultShow;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_SectionViewFullRowSelect;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_SectionViewDetectHiddenSection;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_DetectHiddenSectionStartFromTheEnd;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_LastHiddenSectionLengthHex;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_HiddenSectionStartAtPreviousEnd;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_WriteHiddenSectionConf;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_AutoRefresh;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_AutoRefreshTimerInterval;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_HexInfoDash;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_AutoFindClosestChangedPosition;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_InputIsHexFormat;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UsingLittleEndian;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_ColorTheme;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UiForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_UiBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainToolStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridViewRowIndexForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridViewBackgroundColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridViewBaseRowColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridViewGridColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridCellForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_MainCheatGridCellBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QueryStatusStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QueryAlignmentBoxForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QueryScanBtnBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewFilterForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewFilterBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewFilterSizeForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewFilterSizeBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewExecutableForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewNoNameForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewNoName2ForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewHiddenForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewItemCheck1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_QuerySectionViewItemCheck2BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_HexEditorChangedFinishForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_HexEditorShadowSelectionColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_HexEditorZeroBytesForeColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PointerFinderStatusStrip1BackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_PointerFinderScanBtnBackColor;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description_SendPayloadStatusStrip1BackColor;
    }
}
